### ISSUE TITLE
Differences between low/medium/high for 2020 depths

### ISSUE THREAD

**Issue by mulderphilip** [FirstStreet/fsf_api_access_python#17]
While pulling some flood depth data for 2020 properties, I'm finding that many have different depths listed in 2020 under the low/medium/high scenarios. My understanding was that the low/medium/high correspond to climate severity and so differences should only appear in future flood risk. How should I interpret these differences in 2020 thinking about current flood risk? 

Thank you, happy to provide more info as necessary!

**Comment by mike-amodeo** [comment]
@mulderphilip We quantified the uncertainty within the current climate as well as the future climate. We did this because to get a large enough historical record to accurately estimate extreme events, you have to use multiple decades of observations. However, the climate changes within that record. So our historical observation period is adjusted to get to 2020 based on global climate model projections of what the true climate is in 2020, just as we adjust climate in 2020.

**Comment by mulderphilip** [comment]
Thank you!
