### ISSUE TITLE
Getting FSIDs for specified geometry

### ISSUE THREAD

**Issue by bradleyswilson** [FirstStreet/fsf_api_access_python#38]
Is there a way to get a list of property FSIDs within a given geometry (city, tract, etc?) A lot of features in the API seem to hinge on already knowing FSIDs, and I can't find any information on how to actually get them for a given place.

**Comment by bradleyswilson** [comment]
Looks like this has been resolved, thanks!

**Comment by Lyetenth** [comment]
Hey @bradleyswilson ,

You should have access to a folder with files of different location FSIDs. Let me know if you are unable to access that folder

Also, if you are looking to retrieve `historic` or `adaptation` data for location levels higher than property (Ex: whole states), take a look at using `Historic Event By Location` and `Adaptation Detail By Location` in the [wiki](https://github.com/FirstStreet/fsf_api_access_python/wiki)

For those functions, submitting a single high-level FSID (ex: 19) will retrieve the data for every property within that geographic location instead of needing to input a big list of every property fsid
