### ISSUE TITLE
Confidence score for address lookups? 

### ISSUE THREAD

**Issue by mulderphilip** [FirstStreet/fsf_api_access_python#48]
Hello, 

One (completely understandable) issue we've noticed with address look-ups is that the API will return a match that looks like a false positive on manual inspection. Does the API calculate any sort of confidence score on these address matches that can be pulled with e.g. location_detail in order to prune some of the more questionable matches? 

Thank you,
Philip

**Comment by Lyetenth** [comment]
Hi @mulderphilip,

I checked with the engineering team and unfortunately it doesn't seem like this will be a feature being implemented in the near future. This is because it matches based on the geometry, so it's difficult to accurately assign a score on the address data.

However, I'll keep this issue up for now so we can keep an eye on it

**Comment by mulderphilip** [comment]
Sure, thank you!

Just to follow up with a quick clarification. The case I'm talking about is, say, one enters "1412 Lke Street, 33047" and that gets matched to an FSID where I see from the location details the matched address is "1412 Lake St, Palm Beach, FL 33047". What you're saying is that the API never made the connection between those two address strings?

**Comment by seripap** [comment]
@mulderphilip The address string is reversed geocoded to a lat/lng by a third party service. This coordinate is used to do the lookup in our database, so in a sense yes- the API ignores the inputted address string and does not compare what exists in our database with what is requested.

**Comment by mulderphilip** [comment]
I see, thank you for the clarification
