### ISSUE TITLE
AAL NA Values

### ISSUE THREAD

**Issue by mattswalter** [FirstStreet/fsf_api_access_python#52]
Hello,

When running the AAL for a list of properties, the majority of results for low, mid, and high show as NA.
![image](https://user-images.githubusercontent.com/36939494/112052193-3986fd00-8b29-11eb-86b4-3da299a42d71.png)

However, some properties also show a 0 value instead of an NA. Do NA and 0 both represent $0 loss? What do the NA values represent? 
![image](https://user-images.githubusercontent.com/36939494/112052305-591e2580-8b29-11eb-92ee-ede2f06323c4.png)

Code;
**aal = fs.aal.get_summary(search_items=fsid_list, location_type="property", csv=True)**

Thanks,
Matt

**Comment by Lyetenth** [comment]
Hi Matt,

NA's appear when the flood factor is 1 (or minimal flood risk). For example, `100000001` and `100000004` both have a flood factor of 1. Since they are unlikely to flood, they are unlikely to have any loss due to flood damage.

The 0's however, appear for locations that have a flood factor greater than 1. For example, `100000044` has a flood factor of 7. However, it has a high ground floor elevation, and no basement, so the threshold to trigger damage loss is much higher (and hence $0 in flood damage)

Let me know if that makes sense,
Kelvin

**Comment by mattswalter** [comment]
> Hi Matt,
> 
> NA's appear when the flood factor is 1 (or minimal flood risk). For example, `100000001` and `100000004` both have a flood factor of 1. Since they are unlikely to flood, they are unlikely to have any loss due to flood damage.
> 
> The 0's however, appear for locations that have a flood factor greater than 1. For example, `100000044` has a flood factor of 7. However, it has a high ground floor elevation, and no basement, so the threshold to trigger damage loss is much higher (and hence $0 in flood damage)
> 
> Let me know if that makes sense,
> Kelvin

Hi Kelvin,

Yes, this makes sense. Thanks so much!
