### ISSUE TITLE
Can't access tiles using the API key

### ISSUE THREAD

**Issue by pranjalirai** [FirstStreet/fsf_api_access_python#73]
I am trying to extract map tiles through the API. But, my API key doesn't seem to work
I am running the same code I used to successfully extract tiles last summer. 
Following is the error I am getting:

<Response [403]>
b'{"error":{"code":"403","message":"The user has no policy access to service tile"}}'

Following is the code I am using:

def test():
    url = "https://api.firststreet.org/v1/tile/probability/depth/2020/5/12/942/1715.png"  
    headers = {'authorization': 'Bearer wdztdoawmaowl8j1utpzxzmmyirp6vet'}
    response = requests.request("GET", url, headers=headers) 
    print(response)
    print(response.content)
       
test()

**Comment by Lyetenth** [comment]
Hey @pranjalirai,

You or your supervisor should have received an email on October 14th, 2021, that highlighted that First Street was pulling API access. Please let me know if you are not receiving our email updates.

---
As an organization, First Street has moved away from using the API for data access. We have removed API access for current Research Lab members and have transitioned to a bulk data access delivery. We have discovered after the past trial year period with the API that it is not as seamless as we had hoped. We moved to bulk data delivery in order to expedite the research process. The data will be delivered through an S3 link and will be in CSV format. You can find a sample of the data and the data dictionary [here](https://firststreet.org/data-access/getting-started-with-first-street-data/data-dictionary/).
---

Please let me know if you have outstanding data requests and [Marguerite](mailto:marguerite@firststreet.org) will work to get the data to you. We can send you the flood risk statistics for any area in the 48 contiguous states. We can only send the 100-year hazards for the years 2022, 2037, 2052 for smaller geographic areas.

**Comment by pranjalirai** [comment]
Hey @Lyetenth 
Thanks for replying to my query.
Are map tiles also available by request?

**Comment by Lyetenth** [comment]
Just 100-year for small geographic areas - city county, and maybe state. Your best bet is to send an email to Marguerite (marguerite@firststreet.org) to confirm (and to make the request)
